---

name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: docker compose run --rm app sh -c "./wait-for-db.sh && python manage.py test"

      - name: Lint
        run: docker compose run --rm app sh -c "flake8"

  
